#$ENV:STARSHIP_CONFIG = "$HOME\.starship\starship.toml"
$ENV:STARSHIP_CONFIG = "C:\Users\vphae\OneDrive\Documents\WindowsPowerShell\andrew8088.toml"
#$ENV:STARSHIP_CONFIG = "C:\Users\vphae\OneDrive\Documents\WindowsPowerShell\no-runtime-versions.toml"
#$ENV:STARSHIP_CONFIG = "C:\Users\vphae\OneDrive\Documents\WindowsPowerShell\pastel.toml"
#$ENV:STARSHIP_CONFIG = "C:\Users\vphae\OneDrive\Documents\WindowsPowerShell\starship_emojis.toml"
#$ENV:STARSHIP_CONFIG = "C:\Users\vphae\OneDrive\Documents\WindowsPowerShell\starship.toml"
#$ENV:STARSHIP_CONFIG = "C:\Users\vphae\OneDrive\Documents\WindowsPowerShell\er888kh.toml"
$ENV:STARSHIP_DISTRO = " xcad"
Invoke-Expression (&starship init powershell)

# Personalize the console
$Host.UI.RawUI.WindowTitle = "Powershell " + $Host.Version;

# Draw welcome screen
Write-Host -ForegroundColor DarkYellow "                       _oo0oo_"
Write-Host -ForegroundColor DarkYellow "                      o8888888o"
Write-Host -ForegroundColor DarkYellow "                      88`" . `"88"
Write-Host -ForegroundColor DarkYellow "                      (| -_- |)"
Write-Host -ForegroundColor DarkYellow "                      0\  =  /0"
Write-Host -ForegroundColor DarkYellow "                    ___/`----'\___"
Write-Host -ForegroundColor DarkYellow "                  .' \\|     |// '."
Write-Host -ForegroundColor DarkYellow "                 / \\|||  :  |||// \"
Write-Host -ForegroundColor DarkYellow "                / _||||| -:- |||||- \"
Write-Host -ForegroundColor DarkYellow "               |   | \\\  -  /// |   |"
Write-Host -ForegroundColor DarkYellow "               | \_|  ''\---/''  |_/ |"
Write-Host -ForegroundColor DarkYellow "               \  .-\__  '-'  ___/-. /"
Write-Host -ForegroundColor DarkYellow "             ___'. .'  /--.--\  `. .'___"
Write-Host -ForegroundColor DarkYellow "          .`"`" '<  `.___\_<|>_/___.' >' `"`"."
Write-Host -ForegroundColor DarkYellow "         | | :  `- \`.;`\ _ /`;.`/ - ` : | |"
Write-Host -ForegroundColor DarkYellow "         \  \ `_.   \_ __\ /__ _/   .-` /  /"
Write-Host -ForegroundColor DarkYellow "     =====`-.____`.___ \_____/___.-`___.-'====="
Write-Host -ForegroundColor DarkYellow "                       `=---='"

<#
Write-Host -ForegroundColor DarkYellow " _                ( Hey down there! Don't )"
Write-Host -ForegroundColor DarkYellow " /\\               ( you blockheads know )"
Write-Host -ForegroundColor DarkYellow " \ \\  \__/ \__/  / ( that these things )"
Write-Host -ForegroundColor DarkYellow "  \ \\ (oo) (oo) /    ( CAN'T crash!! )"
Write-Host -ForegroundColor DarkYellow "   \_\\/~~\_/~~\_"
Write-Host -ForegroundColor DarkYellow "  _.-~===========~-._"
Write-Host -ForegroundColor DarkYellow " (___/_______________)"
Write-Host -ForegroundColor DarkYellow "    /  \_______/"
Write-Host -ForegroundColor DarkYellow " ( What a bunch of nuts! )"
Write-Host -ForegroundColor DarkYellow " "
#>
<#
Write-Host -ForegroundColor DarkYellow " __________________▄▄▄▀▀▀▀▀▀▀▄"
Write-Host -ForegroundColor DarkYellow " _______________▄▀▀____▀▀▀▀▄____█"
Write-Host -ForegroundColor DarkYellow " ___________▄▀▀__▀▀▀▀▀▀▄___▀▄___█"
Write-Host -ForegroundColor DarkYellow " __________█▄▄▄▄▄▄_______▀▄__▀▄__█"
Write-Host -ForegroundColor DarkYellow " _________█_________▀▄______█____█_█"
Write-Host -ForegroundColor DarkYellow " ______▄█_____________▀▄_____▐___▐_▌"
Write-Host -ForegroundColor DarkYellow " ______██_______________▀▄___▐_▄▀▀▀▄"
Write-Host -ForegroundColor DarkYellow " ______█________██_______▌__▐▄▀______█"
Write-Host -ForegroundColor DarkYellow " ______█_________█_______▌__▐▐________▐"
Write-Host -ForegroundColor DarkYellow " _____▐__________▌_____▄▀▀▀__▌_______▐_"___________▄▄▄▄▄▄
Write-Host -ForegroundColor DarkYellow " ______▌__________▀▀▀▀________▀▀▄▄▄▀______▄▄████▓▓▓▓▓▓▓███▄"
Write-Host -ForegroundColor DarkYellow " ______▌____________________________▄▀__▄▄█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄"
Write-Host -ForegroundColor DarkYellow " ______▐__________________________▄▀_▄█▓▓▓▓▓▓▓▓▓▓_____▓▓____▓▓█▄"
Write-Host -ForegroundColor DarkYellow " _______▌______________________▄▀_▄█▓▓▓▓▓▓▓▓▓▓▓____▓▓_▓▓_▓▓__▓▓█"
Write-Host -ForegroundColor DarkYellow " _____▄▀▄_________________▄▀▀▌██▓▓▓▓▓▓▓▓▓▓▓▓▓__▓▓▓___▓▓_▓▓__▓▓█"
Write-Host -ForegroundColor DarkYellow " ____▌____▀▀▀▄▄▄▄▄▄▄▄▀▀___▌█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓__▓________▓▓___▓▓▓█"
Write-Host -ForegroundColor DarkYellow " _____▀▄_________________▄▀▀▓▓▓▓▓▓▓▓█████████████▄▄_____▓▓__▓▓▓█"
Write-Host -ForegroundColor DarkYellow " _______█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▓▓▓▓▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██▄▄___▓▓▓▓▓█"
Write-Host -ForegroundColor DarkYellow " _______█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▓▓███▓▓▓▓████▓▓▓▓▓▓▓▓▓▓▓▓▓██▓▓▓▓▓▓█"
Write-Host -ForegroundColor DarkYellow " ________█▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▓█▓▓██░░███████░██▓▓▓▓▓▓▓▓▓▓██▓▓▓▓▓█"
Write-Host -ForegroundColor DarkYellow " ________█▓▓▓▓▓▓▓▓▓▓▓▓▓▓██▓░░░░░█░░░░░██░░░░██▓▓▓▓▓▓▓▓▓██▓▓▓▓▌"
Write-Host -ForegroundColor DarkYellow " ________█▓▓▓▓▓▓▓▓▓▓▓▓▓▓███░░░░░░░░____░██░░░░░░░██▓▓▓▓▓▓▓██▓▓▌"
Write-Host -ForegroundColor DarkYellow " ________▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓██░░░░░░░________░░░░░░░░░██████▓▓▓▓▓█▓▌"
Write-Host -ForegroundColor DarkYellow " ________▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓██░░░░░░___▓▓▓▓▓░░░░░░░███░░███▓▓▓▓▓█▓▌"
Write-Host -ForegroundColor DarkYellow " _________█▓▓▓▓▓▓▓▓▓▓▓▓▓██░░░░░___▓▓█▄▄▓░░░░░░░░___░░░░█▓▓▓▓▓█▓▌"
Write-Host -ForegroundColor DarkYellow " _________█▓▓▓▓▓▓▓▓▓▓▓▓▓█░░█░░░___▓▓██░░░░░░░░▓▓▓▓__░░░░█▓▓▓▓██"
Write-Host -ForegroundColor DarkYellow " _________█▓▓▓▓▓▓▓▓▓▓▓▓▓█░███░░____▓░░░░░░░░░░░█▄█▓__░░░░█▓▓█▓█"
Write-Host -ForegroundColor DarkYellow " _________▐▓▓▓▓▓▓▓▓▓▓▓▓▓█░█████░░░░░░░░░░░░░░░░░█▓__░░░░███▓█"
Write-Host -ForegroundColor DarkYellow " __________█▓▓▓▓▓▓▓▓▓▓▓▓█░░███████░░░░░░░░░░░░░░░▓_░░░░░██▓█"
Write-Host -ForegroundColor DarkYellow " __________█▓▓▓▓▓▓▓▓▓▓▓▓█░░░███████░░░░░░░░░░░░░░_░░░░░██▓█"
Write-Host -ForegroundColor DarkYellow " __________█▓▓▓▓▓▓▓▓▓▓▓▓█░░░███████░░░░░░░░░░░░░░░░░░░██▓█"
Write-Host -ForegroundColor DarkYellow " ___________█▓▓▓▓▓▓▓▓▓▓▓▓█░░░░███████░░░░░░░░░░░█████░██░"
Write-Host -ForegroundColor DarkYellow " ___________█▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░__███████░░░░░███████░░█░░"
Write-Host -ForegroundColor DarkYellow " ___________█▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░█▄▄▄▀▀▀▀████████████░░█░"
Write-Host -ForegroundColor DarkYellow " ___________▐▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░██████▄__▀▀░░░███░░░░░█"
Write-Host -ForegroundColor DarkYellow " ___________▐▓▓▓▓▓▓▓▓▓▓▓█▒█░░░░░░▓▓▓▓▓███▄░░░░░░░░░░░_____________▄▄▄"
Write-Host -ForegroundColor DarkYellow " ___________█▓▓▓▓▓▓▓▓▓█▒▒▒▒█░░░░░░▓▓▓▓▓█░░░░░░░░░░░______▄▄▄_▄▀▀____▀▄"
Write-Host -ForegroundColor DarkYellow " __________█▓▓▓▓▓▓▓▓▓█▒▒▒▒█▓▓░░░░░░░░░░░░░░░░░░░░░____▄▀____▀▄_________▀"
Write-Host -ForegroundColor DarkYellow " _________█▓▓▓▓▓▓▓▓▓█▒▒▒▒█▓▓▓▓░░░░░░░░░░░░░░░░░______▐▄________█▄▄▀▀▀▄__█"
Write-Host -ForegroundColor DarkYellow " ________█▓▓▓▓▓▓▓▓█▒▒▒▒▒▒█▓▓▓▓▓▓▓░░░░░░░░░____________█_█______▐_________▀▄▌"
Write-Host -ForegroundColor DarkYellow " _______█▓▓▓▓▓▓▓▓█▒▒▒▒▒▒███▓▓▓▓▓▓▓▓▓▓▓█▒▒▄___________█__▀▄____█____▄▄▄____▐"
Write-Host -ForegroundColor DarkYellow " ______█▓▓▓▓▓▓▓█_______▒▒█▒▒██▓▓▓▓▓▓▓▓▓▓█▒▒▒▄_________█____▀▀█▀▄▀▀▀___▀▀▄▄▐"
Write-Host -ForegroundColor DarkYellow " _____█▓▓▓▓▓██▒_________▒█▒▒▒▒▒███▓▓▓▓▓▓█▒▒▒██________▐_______▀█_____________█"
Write-Host -ForegroundColor DarkYellow " ____█▓▓████▒█▒_________▒█▒▒▒▒▒▒▒▒███████▒▒▒▒██_______█_______▐______▄▄▄_____█"
Write-Host -ForegroundColor DarkYellow " __█▒██▒▒▒▒▒▒█▒▒____▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒____▒█▓█__▄█__█______▀▄▄▀▀____▀▀▄▄█"
Write-Host -ForegroundColor DarkYellow " __█▒▒▒▒▒▒▒▒▒▒█▒▒▒████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█_______█▓▓█▓▓▌_▐________▐____________▐"
Write-Host -ForegroundColor DarkYellow " __█▒▒▒▒▒▒▒▒▒▒▒███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒_______█▓▓▓█▓▌__▌_______▐_____▄▄____▐"
Write-Host -ForegroundColor DarkYellow " _█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒_____█▓▓▓█▓▓▌__▌_______▀▄▄▀______▐"
Write-Host -ForegroundColor DarkYellow " _█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒███████▓▓█▓▓▓▌__▀▄_______________▄▀"
Write-Host -ForegroundColor DarkYellow " _█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒███▒▒▒▒▒▒▒██▓▓▓▓▓▌___▀▄_________▄▀▀"
Write-Host -ForegroundColor DarkYellow " █▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██▒▒▒▒▒▒▒▒▒▒▒▒▒█▓▓▓▓▓▀▄__▀▄▄█▀▀▀"
Write-Host -ForegroundColor DarkYellow " █▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██▓▓▓▓██▄▄▄▀"
Write-Host -ForegroundColor DarkYellow " █▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒████"
Write-Host -ForegroundColor DarkYellow " █▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█"
Write-Host -ForegroundColor DarkYellow " _█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▄▄▄▄▄"
Write-Host -ForegroundColor DarkYellow " _█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒███▒▒▒▒▒▒██▄▄"
Write-Host -ForegroundColor DarkYellow " __█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒███▒▒▒▒▒▒▒▒▒▒▒▒▒█▄"
Write-Host -ForegroundColor DarkYellow " __█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█"
Write-Host -ForegroundColor DarkYellow " __█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒█▒▒▒▒▒▒▒▒▒██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█"
Write-Host -ForegroundColor DarkYellow " ___█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒█▒▒▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░▒▒▒▒▒▒▌"
Write-Host -ForegroundColor DarkYellow " ____█▒▒▒▒▒▒▒▒▒▒▒▒▒██▒▒▒▒▒▒▒█▒▒▒▒█▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒░░░░░░░░░░░░░▒▒▌"
Write-Host -ForegroundColor DarkYellow " ____█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█████████████▒▒▒▒▒█▒▒▒▒▒▒▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒░▒▌"
Write-Host -ForegroundColor DarkYellow " _____█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█_______▐▒▒▒▒█▒▒▒▒▒▒▒░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▌"
Write-Host -ForegroundColor DarkYellow " ______█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█________█▒▒█▒▒▒▒▒▒░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▌"
Write-Host -ForegroundColor DarkYellow " _______█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█________█▒█▒▒▒▒▒▒░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▌"
Write-Host -ForegroundColor DarkYellow " ________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█________█▒▒▒▒▒▒░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█"
Write-Host -ForegroundColor DarkYellow " _________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█________█▒▒▒▒░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█"
Write-Host -ForegroundColor DarkYellow " _________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█________█▒▒▒░░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▀"
Write-Host -ForegroundColor DarkYellow " __________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█_______█▒░░░▒▒▒▒▒░░░░░░░░▒▒▒█▀▀▀"
Write-Host -ForegroundColor DarkYellow " ___________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█_______█░▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░█▀"
Write-Host -ForegroundColor DarkYellow " ____________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█_______█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▀"
Write-Host -ForegroundColor DarkYellow " _____________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█_______█▒▒▒▒▒▒▒▒▒▒▒▒█▀"
Write-Host -ForegroundColor DarkYellow " _____________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█_______▀▀▀███████▀▀"
Write-Host -ForegroundColor DarkYellow " ______________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█"
Write-Host -ForegroundColor DarkYellow " _______________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█"
Write-Host -ForegroundColor DarkYellow " ________________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█"
Write-Host -ForegroundColor DarkYellow " _________________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█"
Write-Host -ForegroundColor DarkYellow " __________________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██▒█"
Write-Host -ForegroundColor DarkYellow " ___________________█▒▒▒▒▒▒▒▒▒▒▒▒▒██▒▒▒▒█"
Write-Host -ForegroundColor DarkYellow " ___________________█▒▒▒▒▒▒▒▒████▒▒▒▒▒▒▒█"
Write-Host -ForegroundColor DarkYellow " ___________________█████████▒▒▒▒▒▒▒▒▒▒▒█"
Write-Host -ForegroundColor DarkYellow " ____________________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█"
Write-Host -ForegroundColor DarkYellow " ____________________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█"
Write-Host -ForegroundColor DarkYellow " _____________________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▌"
Write-Host -ForegroundColor DarkYellow " _____________________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▌"
Write-Host -ForegroundColor DarkYellow " ______________________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░▌"
Write-Host -ForegroundColor DarkYellow " _______________________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░█"
Write-Host -ForegroundColor DarkYellow " ________________________█▒▒▒▒▒▒▒▒▒▒▒░░░█"
Write-Host -ForegroundColor DarkYellow " __________________________██▒▒▒▒▒▒░░░█▀"
Write-Host -ForegroundColor DarkYellow " _____________________________█░░░░░█▀"
Write-Host -ForegroundColor DarkYellow " _______________________________▀▀▀▀"
#>
